### ISSUE TITLE
update source of "license" field

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub-cli#19]
to improve the detection of license information and proper labeling with SPDX identifiers, we changed the logic on the hub.

under the new logic, we use the Github API to get the SPDX identifier and only fall back on the PyPI field if either (a) Github is unavailable or (b) Github returns "NOASSERTION" (which happens if Github cannot identify the license)

see the hub implementations at https://github.com/chanzuckerberg/napari-hub/pull/109 & https://github.com/chanzuckerberg/napari-hub/pull/103

I believe that this is the package that Github uses to infer license info: https://github.com/licensee/licensee

**Comment by DragaDoncila** [comment]
Closed by #21.
